services:
  postgresql-transaction:
    container_name: postgresql-transaction
    image: postgres
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: samaS1234
      PGDATA: /data/postgres/database1
    volumes:
      - postgres:/data/postgres/database1
    ports:
      - "5432:5432"
    restart: unless-stopped

  postgresql-budget:
    container_name: postgresql-budget
    image: postgres
    environment:
      POSTGRES_DB: budgets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: samaS1234
      PGDATA: /data/postgres/database2
    volumes:
      - postgres:/data/postgres/database2
    ports:
      - "5433:5432"
    restart: unless-stopped

  postgresql-user:
    container_name: postgresql-user
    image: postgres
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: samaS1234
      PGDATA: /data/postgres/database3
    volumes:
      - postgres:/data/postgres/database3
    ports:
      - "5434:5432"
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  budget-tracking-system:
    build:
      context:   ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8761:8761"
      - "8222:8222"
      - "8091:8091"
      - "8070:8070"
      - "8999:8999"
    depends_on:
      - postgresql-transaction
      - postgresql-budget
      - postgresql-user

volumes:
  postgres:
  pgadmin:
