services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: samaS1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  config-server:
    build:
      context:   ./config-server
      dockerfile: Dockerfile
    ports:
      - 8888:8080
    networks:
      - postgres
  discovery:
    build:
      context:   ./discovery
      dockerfile: Dockerfile
    ports:
      - 8761:8080
    networks:
      - postgres
    depends_on:
      - config-server
  gateway:
    build:
      context:   ./gateway
      dockerfile: Dockerfile
    ports:
      - 8222:8080
    networks:
      - postgres
    depends_on:
      - config-server
      - discovery
  transaction:
    build:
      context:   ./transaction
      dockerfile: Dockerfile
    ports:
      - 8091:8080
    networks:
      - postgres
    depends_on:
      - config-server
      - discovery
      - gateway

  budget:
    build:
      context:   ./budget
      dockerfile: Dockerfile
    ports:
      - 8070:8080
    networks:
      - postgres
    depends_on:
      - config-server
      - discovery
      - gateway

  user:
    build:
      context:   ./User-Service
      dockerfile: Dockerfile
    ports:
      - 8999:8080
    networks:
      - postgres
    depends_on:
      - config-server
      - discovery
      - gateway

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
