eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: transaction
          uri: http://localhost:8091
          predicates:
            - Path=/api/transaction/**
        - id: budget
          uri: http://localhost:8070
          predicates:
            - Path=/api/budgets/** , /api/category/**
        - id: wallet
          uri: http://localhost:8092
          predicates:
            - Path=/api/wallet/**
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**,/oauth2/**,/login/oauth2/**

  jwt:
    secret: ${JWT_SECRET}
    expiration: 180000 # 3 minutes

