eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: transaction
          uri: http://localhost:8091
          predicates:
            - Path=/api/transaction/**
        - id: user
          uri: http://localhost:8999
          predicates:
            - Path=/**
        - id: budget
          uri: http://localhost:8070
          predicates:
            - Path=/**
  jwt:
    secret: ${JWT_SECRET}
    expiration: 180000 # 3 minutes

