eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8091
spring:
  application:
    name: transaction
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/transactions-budget
    username: postgres
    password: samaS1234
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${JWT_SECRET}
    expiration: 180000 # 3 minutes
application:
    config:
      budget-url: http://localhost:8222/api/budget
      wallet-url: http://localhost:8222/api/wallet

