eureka:
  instance:
    hostname: budgetbuddy-ri8k.onrender.com
  client:
    service-url:
      defaultZone: https://budgetbuddy-ri8k.onrender.com:8761/eureka


server:
  port: 8091
spring:
  application:
    name: transaction
  datasource:
    url: jdbc:postgresql://dpg-coq45vtjm4es73af3250-a.oregon-postgres.render.com:5432/transaction_yf5f
    username: transaction_yf5f_user
    password: URuyKAU4Ivm0kQ6hGcpFSayFQZDhmm9Q
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
